### ISSUE TITLE
internal error Ticket issued: TSAA/192.168.2.116.2017-04-03.23-08-38.b3415d4b-797a-4af3-82c4-87faa15491ba

### ISSUE THREAD

**Issue by vinitbadge** [mayank93/Twitter-Sentiment-Analysis#3]
Traceback (most recent call last):
  File "C:\Users\vinit bagde\Desktop\Twitter-Sentiment-Analysis-master\Twitter-Sentiment-Analysis-master\front-end\web2py\gluon\restricted.py", line 209, in restricted
    exec ccode in environment
  File "C:/Users/vinit bagde/Desktop/Twitter-Sentiment-Analysis-master/Twitter-Sentiment-Analysis-master/front-end/web2py/applications/TSAA/controllers/default.py", line 178, in <module>
  File "C:\Users\vinit bagde\Desktop\Twitter-Sentiment-Analysis-master\Twitter-Sentiment-Analysis-master\front-end\web2py\gluon\globals.py", line 185, in <lambda>
    self._caller = lambda f: f()
  File "C:\Users\vinit bagde\Desktop\Twitter-Sentiment-Analysis-master\Twitter-Sentiment-Analysis-master\front-end\web2py\gluon\tools.py", line 2783, in f
    return action(*a, **b)
  File "C:/Users/vinit bagde/Desktop/Twitter-Sentiment-Analysis-master/Twitter-Sentiment-Analysis-master/front-end/web2py/applications/TSAA/controllers/default.py", line 97, in addTest
    data=tokenize(Tweet)
  File "applications\TSAA\modules\tokenizer.py", line 13, in tokenize
    f=open(inputFile,'w')
IOError: [Errno 2] No such file or directory: 'C:\\Users\\vinit bagde\\Desktop\\Twitter-Sentiment-Analysis-master\\Twitter-Sentiment-Analysis-master\\front-end\\web2py\\applications\\TSAA\\modules\\ark-tweet-nlp-0.3.2\\tokenized\\qhxwxurcpxnmpdudhpsz'
Error snapshot

**Comment by ayushidalmia** [comment]
Have you placed the tokeniser in the path?

**Comment by sg25mait** [comment]
Hello, i just followed the whole procedure but its showing the same error. where should i put tokeniser?

**Comment by sg25mait** [comment]
nvm got it. You just have to create a folder name tokenized in applications\TSAA\modules\ark-tweet-nlp-0.3.2\tokenized

**Comment by raditya69** [comment]
which path place should i write tokeniser?
i didnt find just in TSAA/modules/PhraseLevel/code/combine.py

@ayushidalmia

**Comment by raditya69** [comment]
@bagde007 applications/TSAA/modules/tokenizer.py

@ayushidalmia i dont get it, which should I paste access token? tyring paste in tokenizer.py but it cant run

**Comment by mayank93** [comment]
Hi, 
Currently I don't have a Windows machine with me. If urgent can you check on linux machine and let me the error.
