### ISSUE TITLE
No such file or directory: '/home/dp/Downloads/Twitter-Sentiment-Analysis-master/front-end/web2py/applications/TSAA/modules/ark-tweet-nlp-0.3.2/tokenized/tffstonfounjqixewlzg'

### ISSUE THREAD

**Issue by darshit7** [mayank93/Twitter-Sentiment-Analysis#4]
While Adding new test from 'Add Test' I got following error. There's not any folder named `tokenized` in `Twitter-Sentiment-Analysis-master/front-end/web2py/applications/TSAA/modules/ark-tweet-nlp-0.3.2/` directory. Am I doing anything wrong?

```
Traceback (most recent call last):
  File "/home/dp/Downloads/Twitter-Sentiment-Analysis-master/front-end/web2py/gluon/restricted.py", line 209, in restricted
    exec ccode in environment
  File "/home/dp/Downloads/Twitter-Sentiment-Analysis-master/front-end/web2py/applications/TSAA/controllers/default.py", line 178, in <module>
  File "/home/dp/Downloads/Twitter-Sentiment-Analysis-master/front-end/web2py/gluon/globals.py", line 185, in <lambda>
    self._caller = lambda f: f()
  File "/home/dp/Downloads/Twitter-Sentiment-Analysis-master/front-end/web2py/gluon/tools.py", line 2783, in f
    return action(*a, **b)
  File "/home/dp/Downloads/Twitter-Sentiment-Analysis-master/front-end/web2py/applications/TSAA/controllers/default.py", line 97, in addTest
    data=tokenize(Tweet)
  File "applications/TSAA/modules/tokenizer.py", line 13, in tokenize
    f=open(inputFile,'w')
IOError: [Errno 2] No such file or directory: '/home/dp/Downloads/Twitter-Sentiment-Analysis-master/front-end/web2py/applications/TSAA/modules/ark-tweet-nlp-0.3.2/tokenized/tffstonfounjqixewlzg'
```

**Comment by darshit7** [comment]
Closed as no response.
